version: "3"

services:
  db:
    image: akvo/akvo-postgres-10.16:latest
    environment:
      - POSTGRES_PASSWORD=akvo
    volumes:
      - pg-data:/var/lib/postgresql/data
  client:
    image: postgres:10.16
    environment:
      - PGSSLMODE=require
      - PGSSLKEY=/pg-data/server.key
      - PGSSLCERT=/pg-data/server.crt
    entrypoint: /bin/bash
    volumes:
      - pg-data:/pg-data
    depends_on:
      - db
volumes:
  pg-data:
